version: '3'
services:
    laravel:
        image: unpamofficial/php:8.1-laravel
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/etc/php/8.1/cli/conf.d/99-sail.ini
        depends_on:
            - mysql
    mysql:
        image: mariadb:10.3
        restart: always
        ports:
            - '${DB_PORT_FORWARD:-3306}:3306'
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-mysql}
            MYSQL_DATABASE: ${DB_DATABASE-laravel}
volumes:
    mysql:
